In [9]:
import fastf1
import pandas as pd

In [82]:
session = fastf1.get_session(2024, 'Silverstone', 'Race')
session.load(telemetry=True, laps=True, weather=True)

core           INFO 	Loading data for British Grand Prix - Race [v3.6.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
_api        WARNING 	Driver 21: Car data is incomplete!
_api        WARNING 	Driver  3: Car data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 21: Position data is incomplete!
_api        WARNING 	Driver  3: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['44', '1', '4', '81', '55', '27', '18', '14', '23', '22', '2', '20', '3', '16', '77', '31', '11', '24', '63', '10']

In [83]:

# Copia base
laps = session.laps.copy()

# Nome completo
laps['FullName'] = laps['Driver'].apply(lambda x: session.get_driver(x)['FullName'])

# Flag de pitstop
laps['PitStopBool'] = laps['PitInTime'].notna()

# PitStops acumulados por piloto
laps['PitStops'] = laps.groupby('Driver')['PitStopBool'].cumsum()

# Posição atual direta
laps['CurrentPosition'] = laps['Position']

# Informação do evento
laps['Country'] = session.event['Country']
laps['Year'] = session.event['EventDate'].year

# Resultados finais da corrida
results = session.results[['DriverNumber', 'Position', 'GridPosition', 'Status']].rename(
    columns={'Position': 'FinalPosition'}
)
laps = laps.merge(results, on='DriverNumber', how='left')

# ==== ✅ CORREÇÃO DO MERGE COM WEATHER ====

# Meio da volta (melhor ponto para casar condições climáticas)
laps['LapMidTime'] = laps['LapStartTime'] + laps['LapTime'] / 2
laps['LapMidTime'] = laps['LapMidTime'].fillna(laps['LapStartTime'])

# Preparar weather
weather = session.weather_data[['Time', 'TrackTemp', 'Rainfall']].copy()

# Garantir ordenação para merge_asof
laps = laps.sort_values('LapMidTime')
weather = weather.sort_values('Time')

# Merge temporal correto
laps = pd.merge_asof(
    laps,
    weather,
    left_on='LapMidTime',
    right_on='Time',
    direction='nearest',
    tolerance=pd.Timedelta(seconds=30)  # ajuste se quiser mais/menos sensibilidade
)

# ==== Seleção das colunas finais ====
cols = [
    'FullName', 'LapTime', 'LapNumber', 'Stint', 'PitStopBool', 'IsPersonalBest', 'Compound', 'TyreLife', 'FreshTyre', 'TrackStatus',
    'CurrentPosition', 'Country', 'Year', 'FinalPosition', 'GridPosition',
    'Status', 'TrackTemp', 'Rainfall'
]

final_df = laps[cols]

display(final_df.head())

,FullName,LapTime,LapNumber,Stint,PitStopBool,IsPersonalBest,Compound,TyreLife,FreshTyre,TrackStatus,CurrentPosition,Country,Year,FinalPosition,GridPosition,Status,TrackTemp,Rainfall
0,Pierre Gasly,NaT,1.0,1.0,False,False,MEDIUM,1.0,True,1,NaN,United Kingdom,2024,20.0,19.0,Did not start,33.0,False
1,George Russell,0 days 00:01:35.211000,1.0,1.0,False,False,MEDIUM,1.0,True,1,1.0,United Kingdom,2024,19.0,1.0,Retired,33.0,False
2,Lewis Hamilton,0 days 00:01:36.034000,1.0,1.0,False,False,MEDIUM,1.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,33.0,False
3,Max Verstappen,0 days 00:01:36.711000,1.0,1.0,False,False,MEDIUM,1.0,True,1,3.0,United Kingdom,2024,2.0,4.0,Finished,33.0,False
4,Lando Norris,0 days 00:01:37.347000,1.0,1.0,False,False,MEDIUM,1.0,True,1,4.0,United Kingdom,2024,3.0,3.0,Finished,33.0,False

In [88]:
final_df[final_df['FullName'] == 'Lewis Hamilton']

,FullName,LapTime,LapNumber,Stint,PitStopBool,IsPersonalBest,Compound,TyreLife,FreshTyre,TrackStatus,CurrentPosition,Country,Year,FinalPosition,GridPosition,Status,TrackTemp,Rainfall
2,Lewis Hamilton,0 days 00:01:36.034000,1.0,1.0,False,False,MEDIUM,1.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,33.0,False
21,Lewis Hamilton,0 days 00:01:31.420000,2.0,1.0,False,True,MEDIUM,2.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,33.0,False
40,Lewis Hamilton,0 days 00:01:31.716000,3.0,1.0,False,False,MEDIUM,3.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,24.3,False
59,Lewis Hamilton,0 days 00:01:31.988000,4.0,1.0,False,False,MEDIUM,4.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,24.0,False
78,Lewis Hamilton,0 days 00:01:31.677000,5.0,1.0,False,False,MEDIUM,5.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,24.2,False
97,Lewis Hamilton,0 days 00:01:31.746000,6.0,1.0,False,False,MEDIUM,6.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,25.4,False
116,Lewis Hamilton,0 days 00:01:31.675000,7.0,1.0,False,False,MEDIUM,7.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,25.8,False
135,Lewis Hamilton,0 days 00:01:31.760000,8.0,1.0,False,False,MEDIUM,8.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,26.1,False
154,Lewis Hamilton,0 days 00:01:31.564000,9.0,1.0,False,False,MEDIUM,9.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,26.0,False
173,Lewis Hamilton,0 days 00:01:31.515000,10.0,1.0,False,False,MEDIUM,10.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,25.6,False
192,Lewis Hamilton,0 days 00:01:31.487000,11.0,1.0,False,False,MEDIUM,11.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,25.4,False
211,Lewis Hamilton,0 days 00:01:31.563000,12.0,1.0,False,False,MEDIUM,12.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,25.2,False
230,Lewis Hamilton,0 days 00:01:31.881000,13.0,1.0,False,False,MEDIUM,13.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,24.9,False
249,Lewis Hamilton,0 days 00:01:31.609000,14.0,1.0,False,False,MEDIUM,14.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,24.6,False
268,Lewis Hamilton,0 days 00:01:31.563000,15.0,1.0,False,False,MEDIUM,15.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,24.6,False
287,Lewis Hamilton,0 days 00:01:31.931000,16.0,1.0,False,False,MEDIUM,16.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,24.3,False
306,Lewis Hamilton,0 days 00:01:33.721000,17.0,1.0,False,False,MEDIUM,17.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,24.3,False
325,Lewis Hamilton,0 days 00:01:35.071000,18.0,1.0,False,False,MEDIUM,18.0,True,1,1.0,United Kingdom,2024,1.0,2.0,Finished,23.9,True
343,Lewis Hamilton,0 days 00:01:43.711000,19.0,1.0,False,False,MEDIUM,19.0,True,1,1.0,United Kingdom,2024,1.0,2.0,Finished,22.9,True
363,Lewis Hamilton,0 days 00:01:40.021000,20.0,1.0,False,False,MEDIUM,20.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.5,True
383,Lewis Hamilton,0 days 00:01:32.156000,21.0,1.0,False,False,MEDIUM,21.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.1,True
401,Lewis Hamilton,0 days 00:01:31.095000,22.0,1.0,False,True,MEDIUM,22.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.0,True
419,Lewis Hamilton,0 days 00:01:31.107000,23.0,1.0,False,False,MEDIUM,23.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.0,True
438,Lewis Hamilton,0 days 00:01:31.635000,24.0,1.0,False,False,MEDIUM,24.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.0,True
456,Lewis Hamilton,0 days 00:01:34.988000,25.0,1.0,False,False,MEDIUM,25.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.0,True
474,Lewis Hamilton,0 days 00:01:40.792000,26.0,1.0,False,False,MEDIUM,26.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,21.5,True
492,Lewis Hamilton,0 days 00:01:45.183000,27.0,1.0,True,False,MEDIUM,27.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,21.4,True
512,Lewis Hamilton,0 days 00:02:00.866000,28.0,2.0,False,False,INTERMEDIATE,1.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,21.1,True
530,Lewis Hamilton,0 days 00:01:40.420000,29.0,2.0,False,False,INTERMEDIATE,2.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,20.9,True
549,Lewis Hamilton,0 days 00:01:40.467000,30.0,2.0,False,False,INTERMEDIATE,3.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,20.7,True
568,Lewis Hamilton,0 days 00:01:41.538000,31.0,2.0,False,False,INTERMEDIATE,4.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,20.7,True
587,Lewis Hamilton,0 days 00:01:42.475000,32.0,2.0,False,False,INTERMEDIATE,5.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,20.7,True
606,Lewis Hamilton,0 days 00:01:42.435000,33.0,2.0,False,False,INTERMEDIATE,6.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,20.7,True
625,Lewis Hamilton,0 days 00:01:42.757000,34.0,2.0,False,False,INTERMEDIATE,7.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,21.2,True
643,Lewis Hamilton,0 days 00:01:42.271000,35.0,2.0,False,False,INTERMEDIATE,8.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,21.3,True
661,Lewis Hamilton,0 days 00:01:41.924000,36.0,2.0,False,False,INTERMEDIATE,9.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,21.2,True
678,Lewis Hamilton,0 days 00:01:39.711000,37.0,2.0,False,False,INTERMEDIATE,10.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,22.5,True
696,Lewis Hamilton,0 days 00:01:37.220000,38.0,2.0,True,False,INTERMEDIATE,11.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,23.8,True
713,Lewis Hamilton,0 days 00:01:57.389000,39.0,3.0,False,False,SOFT,2.0,False,1,3.0,United Kingdom,2024,1.0,2.0,Finished,24.6,False
731,Lewis Hamilton,0 days 00:01:30.318000,40.0,3.0,False,True,SOFT,3.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,24.4,False
748,Lewis Hamilton,0 days 00:01:30.118000,41.0,3.0,False,True,SOFT,4.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,24.2,False
766,Lewis Hamilton,0 days 00:01:29.617000,42.0,3.0,False,True,SOFT,5.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,24.7,False
784,Lewis Hamilton,0 days 00:01:29.793000,43.0,3.0,False,False,SOFT,6.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,25.0,False
802,Lewis Hamilton,0 days 00:01:29.697000,44.0,3.0,False,False,SOFT,7.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,24.5,True
820,Lewis Hamilton,0 days 00:01:29.438000,45.0,3.0,False,True,SOFT,8.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,24.5,True
838,Lewis Hamilton,0 days 00:01:29.641000,46.0,3.0,False,False,SOFT,9.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,25.0,False
856,Lewis Hamilton,0 days 00:01:29.538000,47.0,3.0,False,False,SOFT,10.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,24.9,False
874,Lewis Hamilton,0 days 00:01:29.579000,48.0,3.0,False,False,SOFT,11.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,25.2,False
892,Lewis Hamilton,0 days 00:01:29.667000,49.0,3.0,False,False,SOFT,12.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,25.2,False
909,Lewis Hamilton,0 days 00:01:29.682000,50.0,3.0,False,False,SOFT,13.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,25.4,False
925,Lewis Hamilton,0 days 00:01:29.743000,51.0,3.0,False,False,SOFT,14.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,25.5,False
943,Lewis Hamilton,0 days 00:01:30.146000,52.0,3.0,False,False,SOFT,15.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,25.2,False

In [ ]:
# #final_df['LapTime'] = final_df['LapTime'].dt.total_seconds()
# # Remove as linhas onde o tipo de pneu está como UNKNOWN
# final_df = final_df[final_df['Compound'] != 'UNKNOWN']
# # Removendo voltas que não possuem tempo.
# final_df = final_df[final_df['LapTime'].notna()]
# final_df = final_df.loc[final_df['TrackStatus'] == '1']
# final_df['PitStops'] = final_df['Stint'] - 1

# pitstops = final_df.pop('PitStops')

# final_df.insert(6, 'PitStops', pitstops)

In [106]:
final_df[(final_df['Rainfall'] == True) & (final_df['FullName'] == 'Lewis Hamilton')]

,FullName,LapTime,LapNumber,Stint,PitStopBool,IsPersonalBest,PitStops,Compound,TyreLife,FreshTyre,TrackStatus,CurrentPosition,Country,Year,FinalPosition,GridPosition,Status,TrackTemp,Rainfall
325,Lewis Hamilton,95.071,18.0,1.0,False,False,0.0,MEDIUM,18.0,True,1,1.0,United Kingdom,2024,1.0,2.0,Finished,23.9,True
343,Lewis Hamilton,103.711,19.0,1.0,False,False,0.0,MEDIUM,19.0,True,1,1.0,United Kingdom,2024,1.0,2.0,Finished,22.9,True
363,Lewis Hamilton,100.021,20.0,1.0,False,False,0.0,MEDIUM,20.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.5,True
383,Lewis Hamilton,92.156,21.0,1.0,False,False,0.0,MEDIUM,21.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.1,True
401,Lewis Hamilton,91.095,22.0,1.0,False,True,0.0,MEDIUM,22.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.0,True
419,Lewis Hamilton,91.107,23.0,1.0,False,False,0.0,MEDIUM,23.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.0,True
438,Lewis Hamilton,91.635,24.0,1.0,False,False,0.0,MEDIUM,24.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.0,True
456,Lewis Hamilton,94.988,25.0,1.0,False,False,0.0,MEDIUM,25.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,22.0,True
474,Lewis Hamilton,100.792,26.0,1.0,False,False,0.0,MEDIUM,26.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,21.5,True
492,Lewis Hamilton,105.183,27.0,1.0,True,False,0.0,MEDIUM,27.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,21.4,True
512,Lewis Hamilton,120.866,28.0,2.0,False,False,1.0,INTERMEDIATE,1.0,True,1,3.0,United Kingdom,2024,1.0,2.0,Finished,21.1,True
530,Lewis Hamilton,100.420,29.0,2.0,False,False,1.0,INTERMEDIATE,2.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,20.9,True
549,Lewis Hamilton,100.467,30.0,2.0,False,False,1.0,INTERMEDIATE,3.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,20.7,True
568,Lewis Hamilton,101.538,31.0,2.0,False,False,1.0,INTERMEDIATE,4.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,20.7,True
587,Lewis Hamilton,102.475,32.0,2.0,False,False,1.0,INTERMEDIATE,5.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,20.7,True
606,Lewis Hamilton,102.435,33.0,2.0,False,False,1.0,INTERMEDIATE,6.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,20.7,True
625,Lewis Hamilton,102.757,34.0,2.0,False,False,1.0,INTERMEDIATE,7.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,21.2,True
643,Lewis Hamilton,102.271,35.0,2.0,False,False,1.0,INTERMEDIATE,8.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,21.3,True
661,Lewis Hamilton,101.924,36.0,2.0,False,False,1.0,INTERMEDIATE,9.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,21.2,True
678,Lewis Hamilton,99.711,37.0,2.0,False,False,1.0,INTERMEDIATE,10.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,22.5,True
696,Lewis Hamilton,97.220,38.0,2.0,True,False,1.0,INTERMEDIATE,11.0,True,1,2.0,United Kingdom,2024,1.0,2.0,Finished,23.8,True
802,Lewis Hamilton,89.697,44.0,3.0,False,False,2.0,SOFT,7.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,24.5,True
820,Lewis Hamilton,89.438,45.0,3.0,False,True,2.0,SOFT,8.0,False,1,1.0,United Kingdom,2024,1.0,2.0,Finished,24.5,True

In [102]:
final_df.to_parquet("silverstone_2024.parquet", index=False, compression="gzip")